apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weavework
  namespace: flux-system
spec:
  interval: 1m
  targetNamespace: default
  chart:
    spec:
      chart: weave-gitops
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: weavework
      version: 4.0.x
  values:
    adminuser:
      create: true
      passwordHash: $2y$10$zTRdq9bLcEmGF27exGcKZ.LnSNIOpwV.n5H7tLP4/oyuSRGjTk7Ai
      username: admin
      namespace: flux-system
    rbac:
      create: true
    service:
      create: true
      type: NodePort
      port: 8080
      