apiVersion: v1
kind: Secret
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJhbnNoYWdyYXdhbCIsInBhc3N3b3JkIjoiRG9ja2VyI0A5NDE1IiwiZW1haWwiOiJBY2lkYnVybjE4MjFAZ21haWwuY29tIiwiYXV0aCI6IllXNXphR0ZuY21GM1lXdzZSRzlqYTJWeUkwQTVOREUxIn19fQ==
  name: demo-secret
  namespace: demo
type: kubernetes.io/dockerconfigjson