apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels:
    app: hello-world
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer