apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: demo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/AcidBurn18/fluxcd
  ref:
    branch: main
  secretRef:
    name: flux-system