apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: demo
  namespace: demo
spec:
  interval: 1m
  chart:
    spec:
      chart: ./helmchart/helloworld/
      version: '6.0'
      sourceRef:
        kind: GitRepository
        name: demo
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2
    imagePullSecretsName: docker-secret
    image:
      repository: anshagrawal/demo
      tag: 1.0
      pullPolicy: Always