apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: demo
  namespace: demo
spec:
  interval: 1m
  chart:
    spec:
      chart: ./helmchart/helloworld/
      version: '1.5'
      sourceRef:
        kind: GitRepository
        name: demo
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2
    imagePullSecretsName: demo-secret
    image:
      repository: docker.io/anshagrawal/demo
      tag: '1.0'
      pullPolicy: Always