# Metric Based on CPU Utilization
---
apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: cpu-utilization
  namespace: app-test
spec:
  provider:
    type: prometheus
    address: http://flagger-prometheus.flagger:9090  # Use Prometheus as the provider
  query: |
    sum(rate(container_cpu_usage_seconds_total{namespace="app-test"}[5m])) by (pod)